### ISSUE TITLE
Does NunitXml.TestLogger support multiple results for projects targeting multiple frameworks?

### ISSUE THREAD

**Issue by mcblair** [spekt/nunit.testlogger#24]
With a csproj `<TargetFrameworks>netcoreapp2.0;net461</TargetFrameworks>`.

When `dotnet test --test-adapter-path:NunitXml.TestLogger.1.1.0 --logger:nunit` is ran without `-f netcoreapp2.0` or `-f net461` both sets of tests are ran but the second overwrites the first results xml.

**Comment by mcblair** [comment]
@Faizan2304 Is #25 an acceptable approach? What are your thoughts on this matter?

**Comment by codito** [comment]
+1 for `$(TargetFramework)` instead of timestamp. I think `:` is not allowed in Windows paths.

**Comment by FrankyBoy** [comment]
That's not just a question of having multiple frameworks but having multiple test projects in general. Right now this library always writes to TestResults.xml which overwrites results from any other test project you might have (for instance, I got a project that has multiple test projects for good reason). In the default loggers (like trx) this is solved by creating unique file names by default.

**Comment by codito** [comment]
We could suffix a timestamp if the `logfile` already exists. The only downside is it will harm automation if user explicitly wants the log file to be named in a predictable manner.

**Comment by codito** [comment]
Similar to https://github.com/spekt/nunit.testlogger/pull/25#issuecomment-441032586, we could parameterize `{timestamp}` or `{pid}` if that makes sense.

**Comment by bshurts** [comment]
I just got bit by this. I'm trying to execute all of the test projects in my repository by executing dotnet test on my solution, but each test project overwrites the other and the test results are only for the last test project to execute. I see the PR is up but it hasn't been touched in a while. It also looks like the build is failing. Is there anything I can do to help push this change through?

**Comment by codito** [comment]
@bshurts thanks for your interest. Any help is most welcome! We have an approach discussed in https://github.com/spekt/nunit.testlogger/pull/25#issuecomment-392402898. Next step is to try it out and update the PR.

**Comment by bshurts** [comment]
After looking through the code is the best approach splintering each assembly/framework into different result files or can we just merge all of the results together into one TestResults.xml? The latter is the behavior of the nunit console runner which means a consistent experience for people migrating from the console runner to dotnet test (like me). Merging the results also seems cleaner because you don't need to grab data from an event and munge that into tokens provided on the command line.

**Comment by bshurts** [comment]
So it looks like dotnet test actually creates separate processes for running each assembly. Since we don't have control of the orchestrating process like the nunit console runner does, merging the TestResults.xml would be pretty difficult. I'll go with the separate files. Sorry for the aside. Still getting ramped on how all of these processes interact with each other.

**Comment by bshurts** [comment]
So I pretty much finished everything including writing tests on the older PR before I realized:
1. I don't have permissions to push.
2. It's wildly out-of-date.

So I made a new PR based on the up-to-date code. I haven't added tests yet. Wanted to get feedback on the approach before attempting to translate my tests into the new testing framework.

**Comment by codito** [comment]
@bshurts thanks! Looks great to me. Added one comment around dependency on TestPlatform.ObjectModel assembly version.

**Comment by codito** [comment]
Fixed with https://github.com/spekt/nunit.testlogger/commit/01d71099eae680deb074daed098b1201eb0c6629. Thanks @bshurts for contributing the feature!
