### ISSUE TITLE
utilize nunit3 to generate .xml output

### ISSUE THREAD

**Issue by SidShetye** [spekt/nunit.testlogger#28]
On our CI (Jenkins + nunit plugin), we noticed the output from this nunit3 logger gets mangled up where the assembly name, the class name and the test method names get concatenated in a strange way. This doesn't happen with nunit3 produced xml files. 

I suspect this is because this logger doesn't generate `classname` and `methodname` properties for the `test-case` tags.

e.g. `<test-case id="0-1000" name="MyTest" fullname="My.Namespace.Testfixture.MyTest" methodname="MyTest" classname="My.Namespace.Testfixture" runstate="Runnable" seed="817325879" result="Passed" start-time="2018-01-01 00:00:00Z" end-time="2018-00-00 00:00:10Z" duration="0.015683" asserts="3" />`

IMHO, instead of re-writing the nunit3 xml generator, what do you think about reusing the code from the nunit3 dll itself? To be fair, I haven't peeked inside to comment on it's reusability but working with the nunit3 folks might help.

**Comment by sidshetye** [comment]
> It is possible we're limited by the testcase/testresult properties this logger has access to by default. This is because the logger objects are defined in vstest and generic/common across all frameworks (xunit, nunit etc.). The logger just uses these to generate xml.

The mstest logger (` --logger:"trx"`) is able to generate both `className` (=`classname` in nunit3 xml) and `name` (=`methodname` in nunit3 xml) off the same workflow. A quick google+github search yields [this clue?](https://github.com/Microsoft/vstest/blob/0341da456744f78bba8ff2a25c1cddfc89c87b08/src/Microsoft.TestPlatform.Extensions.TrxLogger/Utility/Converter.cs#L620)

> We can explore if these missing fields can be generated. Would you like to take a first shot at it?

To be honest, I've already spent way more time on the testing internals than I should. I was doing it out of personal curiosity in my 'down time'. Sorry :(

> I'm not sure we can reuse code since we will not have access to the NUnit object model inside the vstest logger infrastructure. We only have the generic TestCase, TestResult objects at our disposal.

To clarify, I meant that the logger can take an explicit dependency on nunit3 and reuse the `NUnit.Engine.Services.NUnit3XmlResultWriter` class.

**Comment by codito** [comment]
Thanks for sharing the code references. Looked at the `NUnit.Engine.Services.NUnit3XmlResultWriter` class. I am still not convinced to get into internals of nunit engine i.e. create `XmlNode` objects which seems to require a serialization of `TestCase` to xml first via [this](https://github.com/nunit/nunit-console/blob/master/src/NUnitEngine/nunit.engine/XmlHelper.cs#L54) in order to just to write the xml report.

I do agree that this logger should meet the [nunit xml v3 specifications](https://github.com/nunit/docs/wiki/Test-Result-XML-Format) as closely as possible. The mstest approach seems suitable to generate classname attributes.

**Comment by codito** [comment]
Classname and MethodName are now available. Fixed with https://github.com/spekt/nunit.testlogger/pull/30
