### ISSUE TITLE
Test is not reported if TestName contains brackets and there are non-whitespace chars after it

### ISSUE THREAD

**Issue by bagittom** [spekt/nunit.testlogger#57]
E.g.:

This test is not reported:
[TestCase(Description = "Description", TestName = "Test Name (sg within bracket) sg after brackets")]

However this is OK:
[TestCase(Description = "Description", TestName = "Test Name (sg within bracket)")]

**Comment by Siphonophora** [comment]
Hi, 

Our current pre-release package (available at the link below) should log this test. That said, because the name parser is looking for legal c# method names, it will complain that it doesn't understand the name. Therefore, it won't be able to parse out the type or namespace from the method, and will leave type and namespace as 'Unkown'

 https://www.myget.org/feed/spekt/package/nuget/NunitXml.TestLogger

**Comment by codito** [comment]
Fix available in https://www.nuget.org/packages/NunitXml.TestLogger/2.1.62. Sorry for the delay.
